management:
  health.db.enabled: false
  endpoints:    
    web:
      base-path: /
      exposure:
        include: "*"

server:
  port: 7070
  servlet:
    context-path: /api/flights/itineraries-search
  compression:
    enabled: true
    mime-types: application/json
  http2.enabled: true

jetty:
  threadPool:
    maxThreads: 10
    minThreads: 10
    
chaos:
  monkey:
    enabled: false
    watcher:
      restController: true
    assaults:
      exceptionsActive: true
      latencyActive: true   
      latencyRangeStart: 10
      latencyRangeEnd: 12000  
      
spring:
  profiles:
    active: default

connector:  
   provider-alpha:
      host: localhost:8070
      responseTimeout: 5000
      connectionTimeout: 5000
      readTimeout: 5000         
   provider-beta:
      host: localhost:9070
      responseTimeout: 5000
      connectionTimeout: 5000
      readTimeout: 5000


resilience4j:
  ratelimiter:
    configs:
      default:
        timeoutDuration: 1000
        registerHealthIndicator: true
        limitRefreshPeriod: 15s
        limitForPeriod: 2
  circuitbreaker:
    instances:
      provider-beta:
        failureRateThreshold: 50
        registerHealthIndicator: true
        ringBufferSizeInHalfOpenState: 2
        ringBufferSizeInClosedState: 4
        waitDurationInOpenState: 10000
        recordExceptions:
          - java.lang.RuntimeException
          - java.lang.InterruptedException
          - io.netty.handler.timeout.ReadTimeoutException
          - org.springframework.web.reactive.function.client.WebClientRequestException
          - com.twa.flights.api.itineraries.search.exception.TWAException
      provider-alpha:
        failureRateThreshold: 50
        registerHealthIndicator: true
        ringBufferSizeInHalfOpenState: 2
        ringBufferSizeInClosedState: 4
        waitDurationInOpenState: 10000
        recordExceptions:
          - java.lang.RuntimeException
          - java.lang.InterruptedException
          - io.netty.handler.timeout.ReadTimeoutException
          - org.springframework.web.reactive.function.client.WebClientRequestException
          - com.twa.flights.api.itineraries.search.exception.TWAException